### ISSUE TITLE
`ls`: make `LS_OPTION_PRINT_QUESTION_MARKS` non-default for Windows

### ISSUE THREAD

**Issue by lifenjoiner** [minoca/swiss#3]
This is an interesting tool kit with different flavor from Cygwin/MSYS, and seems a bit like busybox-w32. It's definitely another great implementation.

Back to the topic.
On an OEM encoding Windows, there usually are non-ASCII characters for the file/dir names.
https://github.com/minoca/swiss/blob/ff1fc5dd406abeeceaa91e4e3cf5a9b64824fb3f/src/ls/ls.h#L197-L198
https://github.com/minoca/swiss/blob/ff1fc5dd406abeeceaa91e4e3cf5a9b64824fb3f/src/ls/ls.c#L1971-L1972
https://github.com/minoca/swiss/blob/ff1fc5dd406abeeceaa91e4e3cf5a9b64824fb3f/src/ls/ls.c#L1824-L1832
This will cause the characters unreadable.
They can be displayed correctly. I've modified the binary, and it works well.
"Non-printable characters and tabs" shouldn't be file/dir names.
What do you think?

**Comment by evangreen** [comment]
Hi, thanks for taking a look! It sounds like you're proposing removing `LS_OPTION_PRINT_QUESTION_MARKS` from the default set for terminals. I'm open to that. I think I added it in the default because I didn't feel like figuring out the column size computation for multibyte characters or names with tabs in them (see `LS_OPTION_COLUMN_OUTPUT`). Feel free to submit an MR, ideally that also addresses the column width issue that would be unmasked by the change.
