### ISSUE TITLE
`\e` and `\x1b` do not work for `echo -e`

### ISSUE THREAD

**Issue by lifenjoiner** [minoca/swiss#4]
```sh
echo -e "\033[31mHello\e[0m World"
```
`\033` works.

Ref: https://misc.flogisoft.com/bash/tip_colors_and_formatting

**Comment by evangreen** [comment]
Yeah, I think I just implemented the set specified by POSIX [1] rather than the GNU set [2], and then added `-e` in without looking again. Feel free to submit an MR, looks pretty straightforward to add.

[1] https://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html
[2] https://linux.die.net/man/1/echo

**Comment by lifenjoiner** [comment]
I'm mainly a Windows dev, and weren't sensitive on the differences between POSIX and GNU.

Seems it's cheap to have the compatibility, and you are open to it. I had a try.

BTW, 2024 version of POSIX [1] `echo` specification: https://pubs.opengroup.org/onlinepubs/9799919799/utilities/echo.html
